const express = require("express");
const exerciseController = require("../controllers/exerciseController");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const Exercise = require("../models/exercise");
const path = require("path");
const dotenv = require("dotenv");
const mongoose = require("mongoose");

console.log("Directory:", __dirname);

const result = dotenv.config({ path: path.resolve(__dirname, "../.env") });

if (result.error) {
  console.log("🚨 dotenv error:", result.error.message);
} else {
  console.log(
    "✅ dotenv loaded file from:",
    path.resolve(__dirname, "../.env"),
  );
  console.log(
    "🔑 Key loaded by dotenv starts with:",
    result.parsed.GEMINI_API_KEY?.substring(0, 8),
  );
  console.log(
    "🌍 Key ACTUALLY in process.env starts with:",
    process.env.GEMINI_API_KEY?.substring(0, 8),
  );
}

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

console.log("GEMINI_API_KEY in exerciseRoutes: ", process.env.GEMINI_API_KEY);

const router = express.Router();

router.get("/", exerciseController.getAllExercises);
router.post("/", exerciseController.createExercises);
router.delete("/:id", exerciseController.deleteExercise);
router.patch("/:id", exerciseController.updateExercise);

router.get("/topic/:topicName", exerciseController.getExercisesByTopic);
router.post("/execute", exerciseController.executeExercise);
router.post("/detect-struggling", exerciseController.detectStruggling);
router.get("/10-random", exerciseController.get10RandomExercises);

// router.get("/all-to-be-surveyed", async (req, res) => {
//   try {
//     const exercises = await Exercise.find()
//       .lean()
//       .select("title description topic difficulty -_id");

//     res.json(exercises);
//   } catch (error) {
//     console.error("Error fetching exercises to be surveyed:", error);
//     res.status(500).json({ error: "Failed to fetch exercises" });
//   }
// });

// router.post("/update-starter-code-form", async (req, res) => {
//   try {
//     const exercises = await Exercise.find().lean();

//     const exercisesData = exercises.map((exercise) => ({
//       id: exercise._id,
//       title: exercise.title,
//       description: exercise.description,
//       starterCode: exercise.starterCode,
//     }));

//     const model = genAI.getGenerativeModel({
//       model: "gemini-3-flash-preview",
//     });

//     const prompt = `You are an assistant for updating starter code for coding exercises. You will be given a list of exercises with their current starter code. For each exercise, analyze the title and description, and update the starter code to be in python syntax like the following: def function_name(input: type) -> output_type:. If the starter code is already in python code, leave it as it is. Here is the list of exercises:\n\n${JSON.stringify(exercisesData)}\n\nReturn a JSON array with the following format: [{id: _id, updatedStarterCode: "the updated starter code"}].
//     Data Integrity Rule: the id must be exactly equal to the _id string provided to you for each exercise. Do not modify, truncate, or hallucinate the ID. It must remain exactly 24 characters long.`;

//     const result = await model.generateContent(prompt);
//     const response = await result.response;
//     let text = response.text();

//     console.log("Received response from Gemini API: ", text);

//     text = text.replaceAll("`", "").replace("json", "");
//     console.log("Type of text: ", typeof text);
//     console.log("Cleaned response text: ", JSON.parse(text));

//     const updates = JSON.parse(text);
//     for (const update of updates) {
//       if (!mongoose.Types.ObjectId.isValid(update.id)) {
//         console.warn(`⚠️ Skipping invalid ID generated by AI: ${update.id}`);
//         continue;
//       }

//       await Exercise.findByIdAndUpdate(update.id, {
//         starterCode: update.updatedStarterCode,
//       });
//     }

//     // const updates = JSON.parse(text);
//     // res.json({ updates });
//     return res.json({
//       message: "Starter code update process completed",
//       response: text,
//     });
//   } catch (error) {
//     console.log("Error in /update-starter-code-form route: ", error);
//     return res
//       .status(500)
//       .json({ error: "Failed to update starter code form" });
//   }
// });

module.exports = router;
